join_message: '&8[&aIZ&8] &7%player%'
leave_message: '&8[&cIZ&8] &7%player%'
chat_format: '%player% -> %message%'
commandspy:
  filters:
    default:
    - 'c give'
    - 'c i'
    - 'c item'
    all:
    - '*'
  players:
    bobmandude9889:
      filter: default
colors:
  - 'Visitor,7'
  - 'Member,a'
  - 'MemberP,2'
  - 'Trusted,b'
  - 'Mod,c'
  - 'Admin,9'
  - 'Owner,4'
  
ranks:
  - "&7Visitor"
  - "&aMember"
  - "&a&lMember Plus"
  - "&bTrusted"
  - "&9Mod"
  - "&cAdmin"
  - "&4Owner"

inventory_interact_worlds:
  - "spawn"