name: VintageHub
version: 1.0
main: net.bobmandude9889.Main.Main
author: bobmandude9889
depend: [Multiverse-Core,PermissionsEx,PlotMe,Vault]

commands:
  commandspy:
    description: commandspy
    usage: /<command>
    aliases: ['commandpsy','cs']
  lel:
    description: lol
    usage: /<command>
    aliases: ['lawl']
  createclock:
    description: creates a clock
    usage: /<command>
  plots:
    description: warps to plots
    usage: /<command>
  report:
    description: used to report problems
    usage: /<command>
  setfloor:
    description: Change the floor of your plot
    usage: /<command> <blockid>
  kit:
    description: Create and use kits
    usage: /<command> <kit name>
    aliases: [kits]
  gkit:
    description: Create and remove global kits
    usage: /<command> <create,remove> <kit name>
  trusted:
    description: Warp to trusted world
    usage: /<command>
    aliases: [void]

permissions:
  commandspy.use:
    description: gives access to /commandspy
    default: OP
  stap:
    description: stap
    default: OP
  clock.create:
    description: gives access to /createclock
    default: OP
  setfloor.others:
    description: Set other player plot floor
    default: OP
  kit.use:
    description: Use kits
    default: OP
  gkit.use:
    description: Create and remove gkits
    default: OP