name: IZenith
version: 1.0
main: net.bobmandude9889.Main.Main
author: bobmandude9889
depend: [Multiverse-Core,PermissionsEx,PlotSquared,Vault,Essentials]

commands:
  commandspy:
    description: Commandspy
    usage: /<command>
    aliases: ['commandpsy','cs']
  lel:
    description: Lol
    usage: /<command>
    aliases: ['lawl']
  createclock:
    description: creates a clock
    usage: /<command>
  plots:
    description: Warps to plots
    usage: /<command>
  report:
    description: Used to report problems
    usage: /<command>
  setfloor:
    description: Change the floor of your plot
    usage: /<command> <blockid>
  kit:
    description: Create and use kits
    usage: /<command> <kit name>
    aliases: [kits]
  gkit:
    description: Create and remove global kits
    usage: /<command> <create,remove> <kit name>
  trusted:
    description: Warp to trusted world
    usage: /<command>
    aliases: [void]
  ranks:
    description: List servers ranks
    usage: /<command>
  suspend:
    description: Suspend a player
    usage: /<command>
  ip:
    description: Shows the server's Ip Address
    usage: /<command>
  info:
    description: Warp to info
    usage: /<command>
  donated:
    description: Player donated
    usage: /<command>
  worldeditperms:
    description: Add WE perms
    usage: /<command>
  addplot:
    description: Access to another plot
    usage: /<command>

permissions:
  commandspy.use:
    description: gives access to /commandspy
    default: OP
  clock.create:
    description: Gives access to /createclo
    default: OP
  setfloor.others:
    description: Set other player plot floor
    default: OP
  kit.use:
    description: Use Kits
    default: OP
  gkit.use:
    description: Create and remove Global Kits
    default: OP
  hub.suspend:
    description: Suspend players
    default: OP
  report.admin:
    description: gives acces to /report list and remove
    default: OP
